Repository test-kitchen/test-kitchen, pull requests merged in 2018-03, with the labels that each got.

#1373 Update and fix appveyor
  appveyor.yml
Labels: Developing

#1379 Rubocop appeasement
  .rubocop.yml
  Gemfile
  lib/kitchen/cli.rb
  lib/kitchen/command.rb
  lib/kitchen/driver/exec.rb
  lib/kitchen/driver/proxy.rb
  lib/kitchen/lazy_hash.rb
  lib/kitchen/logger.rb
  lib/kitchen/provisioner/chef/berkshelf.rb
  lib/kitchen/provisioner/chef/librarian.rb
  lib/kitchen/provisioner/chef/policyfile.rb
  lib/kitchen/provisioner/chef_solo.rb
  spec/kitchen/provisioner/chef_base_spec.rb
Labels: Developing

#1369 honor root_path for location of chef installer script
  lib/kitchen/provisioner/chef_base.rb
Labels: Reviewing

#1371 Support IPv6 addresses for WinRM
  lib/kitchen/transport/winrm.rb
  spec/kitchen/transport/winrm_spec.rb
Labels: Transport: WinRM
